### PR TITLE
Simplify IsValidSimpleAssignmentTarget to IsSimpleAssignmentTarget.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Based on https://github.com/tc39/ecma262/pull/1652

@rkirsling

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
It made it a little easier 😄

**Comment by ljharb** [comment]
@DanielRosenwasser it was very premature to merge this, as I am very strongly against it being a boolean, and don't intend to merge the spec change as-is.

**Comment by DanielRosenwasser** [comment]
Sorry about that! If that other thread closes I suppose I'll revert the nullish coalescing one, go to v2 on this one.

**Comment by ljharb** [comment]
Easy enough to fix, so nbd, but in general please only adapt proposal specs to what's merged into 262 master :-)

**Pull request merged**
