### PR TITLE
Fix broken link of Angular in Prior Art section

### PR DESCRIPTION
**Pull request by masoud-msk**

### CODE REVIEW

**Comment by ljharb** [comment]
Has an upstream issue been filed on angular for breaking a URL?

**Comment by masoud-msk** [comment]
> Has an upstream issue been filed on angular for breaking a URL?

Didn't check. I was reading the proposal and noticed the broken link, then found it and replaced it.

**Comment by ljharb** [comment]
Thanks - would you mind filing one?

**Comment by masoud-msk** [comment]
Actually I do!
I have no experience in Angular and was merely checking out some examples of this proposal. Just felt like I could improve this proposal a little bit for future readers without much efforts, so I did this and can't spend more time on this.

**Comment by ljharb** [comment]
Fair enough. I spent about 30 seconds and filed https://github.com/angular/angular/issues/38393.

**Comment by claudepache** [comment]
Superseded by #145.

**Pull request closed without merging**
