### PR TITLE
Stage 2!

### PR DESCRIPTION
**Pull request by harsh-tamr**
Update readme to say stage 2

### CODE REVIEW

**Comment by ovidb** [comment]
WWWWWOOOOOOOOOOOOOOOOOOWWWWWWWWWWW!!!!!!!!!!!!!!!
Congrats guys!!!

**Comment by ammanvedi** [comment]
peng

**Comment by MatthiasKunnen** [comment]
That's https://github.com/tc39/proposal-optional-chaining/blob/master/spec.html#L20

**Comment by dustinsavery** [comment]
@jridgewell should be added as an author also, he took this bad boy home

**Comment by jridgewell** [comment]
@dustinsavery: being the champion is different than being the author(s). I’ve not actually written anything, i’ve Only guided it on as I saw best.

**Pull request merged**
