### PR TITLE
proposal moves forward to stage 3 \o/

### PR DESCRIPTION
**Pull request by bcoe**
Amazing work authors @claudepache, @the_gisenberg, @dustinsavery, and
champions @DanielRosenwasser and @jridgewell :tada:.

### CODE REVIEW

**Comment by Mouvedia** [comment]
…after all the issues raised were put to rest by [committing 3 lines in the README](b7529f2).
`?.[]` is inconsistent and a terrible addition to my language.

Not many TC39 proposals have 70 issues closed. That number alone should make you wonder…

**Comment by Whobeu** [comment]
I hope this can make it into some version of Node 12.x.x. I've used this feature extensively in C# and it would be nice to reduce a lot of null checks in my JS modules.

**Comment by GaryGSC** [comment]
@Whobeu Unfortunately, that isn't very likely. This proposal would likely need to be implemented in V8, which is used by Node.

According to [Node's roadmap](https://github.com/nodejs/node/issues/25082), they're planning on stopping at V8 version 7.6 for Node 12, which has already been released and doesn't implement this proposal. 🙁

Basically, Node 12 enters LTS before they'll be able to get to it.

**Comment by Whobeu** [comment]
> @Whobeu Unfortunately, that isn't very likely. This proposal would likely need to be implemented in V8, which is used by Node.
> 
> According to [Node's roadmap](https://github.com/nodejs/node/issues/25082), they're planning on stopping at V8 version 7.6 for Node 12, which has already been released and doesn't implement this proposal. 

According to the link at https://github.com/v8/v8/commit/ceb7bd59432a340ea3711ef5acb8c148471eee8c, Optional Chaining is now implemented in 7.6.77. They move fast! If they take the final 7.6 in at the LTS release of Node 12, maybe that will make it in.

**Comment by GaryGSC** [comment]
Hey, guess what? Node 12 is ahead of their projected schedule. There's now an in-progress [PR to backport V8 7.8 to Node 12](https://github.com/nodejs/node/pull/30109), which supports optional chaining behind the V8 flag `--harmony-optional-chaining`.

**Comment by Whobeu** [comment]
I wonder if Nullish Coalescing made it in too. There was some work done in one of the 7.8 revs to support it. Great to see Optional Chaining.

**Comment by gisenberg** [comment]
@Whobeu It looks like nullish coalescing is included in that PR as well.

**Pull request merged**
