### PR TITLE
Mark as Stage 3 Draft

### PR DESCRIPTION
**Pull request by bennyn**
According to [this page](https://tc39.es/proposal-optional-chaining/) the proposal is in Stage 3 and not in Stage 4.

### CODE REVIEW

**Comment by rolivo** [comment]
You are crazy, this proposal has already reached phase 4 and is integrated with the 2020 version of the standard, please do not do stupid things, thanks.

**Comment by mAAdhaTTah** [comment]
@rolivo That is incredibly rude and uncalled for.

@bennyn Optional chaining has only recently advanced to Stage 4, so not all references have been updated to reflect this, but it will be included in the next version of the spec.

**Comment by biolauri** [comment]
@bennyn, you could request that their page reflect the latest spec by opening an issue on [tc39/tc39.github.io/issues](https://github.com/tc39/tc39.github.io/issues).

You can find [the latest tc39 spec with Optional Chaining](https://tc39.es/ecma262/#sec-optional-chains) to be sure that it reached stage 4. Their [list of finished proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md) does also contain Optional Chaining.

**Comment by Whobeu** [comment]
> According to [this page](https://tc39.es/proposal-optional-chaining/) the proposal is in Stage 3 and not in Stage 4.

On the page you reference, there is [a link](https://github.com/tc39/proposal-optional-chaining/) to [https://github.com/tc39/proposal-optional-chaining/](https://github.com/tc39/proposal-optional-chaining/) that says Stage 4. The page you reference has not been updated but what it references, has.

**Comment by claudepache** [comment]
@bennyn Thank you for having noticed that there was a discrepancy between the spec text and the explainer. I’ve opened #128 in order to correct this.

**Pull request closed without merging**
